### ISSUE TITLE
Can the imgur links generated at each screenshot be stored in a log file of some sort?

### ISSUE THREAD

**Issue by crashhacker1** [ShoelaceMan/MagickShot#1]

**Comment by ShoelaceMan** [comment]
Hello,

As of commit 9423d253b03ba9cdb6cd4b6b3ff43a9c799acea1, this is unnecessary, as the delete hash, and imgur link are stored in the image metadata.

**Comment by crashhacker1** [comment]
> Hello,
> 
> As of commit [9423d25](https://github.com/ShoelaceMan/MagickShot/commit/9423d253b03ba9cdb6cd4b6b3ff43a9c799acea1), this is unnecessary, as the delete hash, and imgur link are stored in the image metadata.

thank you.
